#ifndef FUNCTIONCODES_H
#define FUNCTIONCODES_H

#define START_BYTE 1
#define STOP_BYTE 4


#define OPEN_VIDEO 10
#define GET_FRAME 11

#define SET_PATTERN_SIZE 12
#define ADD_SAMPLE_TO_CALIBRATION 13
#define CALIBRATE_CAMERA 14
#define LOAD_CALIBRATION 15

#define CREATE_VISO_OBJECT 16
#define ADD_IMG_TO_ODOMETRY 17
#define CHANGE_PARAMETERS 18
#define RESET_POSE 19

#define CONTINUOUS_STREAM 20
#endif // FUNCTIONCODES_H
